### ISSUE TITLE
fix: Css marker at the time of blank data

### ISSUE THREAD

**Issue by toshirot** [toshirot/ccchart#4]
http://ngw.jp/~tato/wp/?p=3687

**Comment by Razored** [comment]
Thank you for working on a solution of representing 'no value' on the chart. The current solution (as I see it now by placing single quotes ('') or double quotes ("") before a comma(,)) gives the value of '0' to the 'no value' value and displays it on the chart.

E.g. when reporting annual data for various projects (series) that have different starting dates, eg.: 
["years",2010,2011,2012,2013],
["project1",novalue,100,200,300,400],
["project2",novalue,novalue,200,300]

What is the value to use instead of 'novalue' to make the script display nothing for the project's data series in the corresponding year?

'No data' here does not mean that it is zero (0), it means we have no data for that period. We do not know what the data was in that period, so we cannot state it was zero (0).

**Comment by toshirot** [comment]
data of space sample 
http://jsfiddle.net/UkdvS/535/
